#! /usr/bin/env python3

from sys import argv as av
from datetime import datetime
from os import remove

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'



def princ(color, text):
    print(color + text + bcolors.ENDC, end="")

def printer(f):
    princ(bcolors.BOLD + bcolors.HEADER, f.read(11))
    princ(bcolors.OKBLUE, f.read(3))
    princ(bcolors.WARNING, f.read() + "\n")

def catch(av):

    for i in range(0, len(av)):
        if av[i] == "delete":
            try:
                remove(".not")
            except:
                print("You don't have any notes")
            exit(0)

        if av[i] == "check":
            try:
                pass
            except:
                pass
        if av[i] == "cancel":
            pass



def start(av):

    catch(av)

    try:
        f = open(".not", "r")

        printer(f)
        f.close()
    except:
        f = open(".not", "a")
        note = input()
        date = datetime.now().strftime("%d/%m %H:%M") + " >> "

        f.write(date)
        f.write(note)
        f.close()

if __name__ == "__main__":
    start(av)